//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektniZadatakA.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektniZadatakA.Properties.Langs.Language1", typeof(Language1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj meč.
        /// </summary>
        public static string add_match {
            get {
                return ResourceManager.GetString("add match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj skauta.
        /// </summary>
        public static string add_scout {
            get {
                return ResourceManager.GetString("add scout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takmičenje:.
        /// </summary>
        public static string competition {
            get {
                return ResourceManager.GetString("competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Završi izvještaj.
        /// </summary>
        public static string complete_review {
            get {
                return ResourceManager.GetString("complete_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaključak:.
        /// </summary>
        public static string conclusion {
            get {
                return ResourceManager.GetString("conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Država.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum utakmice:.
        /// </summary>
        public static string date_of_match {
            get {
                return ResourceManager.GetString("date_of_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalna ocjena.
        /// </summary>
        public static string finaly_grade {
            get {
                return ResourceManager.GetString("finaly_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noga.
        /// </summary>
        public static string foot {
            get {
                return ResourceManager.GetString("foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gost:.
        /// </summary>
        public static string guest {
            get {
                return ResourceManager.GetString("guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o gostu:.
        /// </summary>
        public static string guest_information {
            get {
                return ResourceManager.GetString("guest_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaćin:.
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacije o domaćinu:.
        /// </summary>
        public static string host_information {
            get {
                return ResourceManager.GetString("host_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenca.
        /// </summary>
        public static string licence {
            get {
                return ResourceManager.GetString("licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIJAVA NA SISTEM.
        /// </summary>
        public static string login_to_the_system {
            get {
                return ResourceManager.GetString("login_to_the_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odjavi se.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi izvještaj.
        /// </summary>
        public static string make_review {
            get {
                return ResourceManager.GetString("make_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meč.
        /// </summary>
        public static string match {
            get {
                return ResourceManager.GetString("match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utakmice.
        /// </summary>
        public static string matches {
            get {
                return ResourceManager.GetString("matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentalitet.
        /// </summary>
        public static string mentality {
            get {
                return ResourceManager.GetString("mentality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentalne karakteristike:.
        /// </summary>
        public static string mentality_description {
            get {
                return ResourceManager.GetString("mentality_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentalitet ocjena:.
        /// </summary>
        public static string mentality_grade {
            get {
                return ResourceManager.GetString("mentality_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalnost.
        /// </summary>
        public static string nationality {
            get {
                return ResourceManager.GetString("nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacije.
        /// </summary>
        public static string operations {
            get {
                return ResourceManager.GetString("operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šifra:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizika.
        /// </summary>
        public static string physique {
            get {
                return ResourceManager.GetString("physique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizičke karakteristike:.
        /// </summary>
        public static string physique_description {
            get {
                return ResourceManager.GetString("physique_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fizika ocjena:.
        /// </summary>
        public static string physique_grade {
            get {
                return ResourceManager.GetString("physique_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijavljeni skauti:.
        /// </summary>
        public static string registered_scouts {
            get {
                return ResourceManager.GetString("registered_scouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvještaj napravio.
        /// </summary>
        public static string review_by {
            get {
                return ResourceManager.GetString("review_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izvještaji.
        /// </summary>
        public static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skauti.
        /// </summary>
        public static string scouts {
            get {
                return ResourceManager.GetString("scouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srpski.
        /// </summary>
        public static string serbian {
            get {
                return ResourceManager.GetString("serbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadion.
        /// </summary>
        public static string stadium {
            get {
                return ResourceManager.GetString("stadium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadion:.
        /// </summary>
        public static string stadiumm {
            get {
                return ResourceManager.GetString("stadiumm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taktika.
        /// </summary>
        public static string tactics {
            get {
                return ResourceManager.GetString("tactics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taktičke karakteristike:.
        /// </summary>
        public static string tactics_description {
            get {
                return ResourceManager.GetString("tactics_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taktika ocjena:.
        /// </summary>
        public static string tactics_grade {
            get {
                return ResourceManager.GetString("tactics_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekipa.
        /// </summary>
        public static string team {
            get {
                return ResourceManager.GetString("team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehnika.
        /// </summary>
        public static string technique {
            get {
                return ResourceManager.GetString("technique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehničke karakteristike:.
        /// </summary>
        public static string technique_description {
            get {
                return ResourceManager.GetString("technique_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehnika ocjena:.
        /// </summary>
        public static string technique_grade {
            get {
                return ResourceManager.GetString("technique_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema 1.
        /// </summary>
        public static string theme1 {
            get {
                return ResourceManager.GetString("theme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema 2.
        /// </summary>
        public static string theme2 {
            get {
                return ResourceManager.GetString("theme2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema 3.
        /// </summary>
        public static string theme3 {
            get {
                return ResourceManager.GetString("theme3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena karte.
        /// </summary>
        public static string ticket_price {
            get {
                return ResourceManager.GetString("ticket price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena karte (KM):.
        /// </summary>
        public static string ticket_pricekm {
            get {
                return ResourceManager.GetString("ticket_pricekm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godina osnivanja:.
        /// </summary>
        public static string year_founded {
            get {
                return ResourceManager.GetString("year_founded", resourceCulture);
            }
        }
    }
}
